### PR TITLE
[performance] Improve the performance of damerau_levenshtein

### PR DESCRIPTION
**Pull request by lovasoa**
My tests show the new version is approximately 2.5 times faster than
the old one. Most of the gains come from using hashbrown for the
hashmap.

### CODE REVIEW

**Comment by lovasoa** [comment]
@dguo 

Cargo bench after:
```
test benches::bench_damerau_levenshtein            ... bench:       8,208 ns/iter (+/- 774)
test benches::bench_hamming                        ... bench:          72 ns/iter (+/- 8)
test benches::bench_jaro                           ... bench:       1,001 ns/iter (+/- 225)
test benches::bench_jaro_winkler                   ... bench:         994 ns/iter (+/- 85)
test benches::bench_levenshtein                    ... bench:       1,523 ns/iter (+/- 95)
test benches::bench_levenshtein_on_u8              ... bench:       1,680 ns/iter (+/- 233)
test benches::bench_normalized_damerau_levenshtein ... bench:       8,874 ns/iter (+/- 641)
test benches::bench_normalized_levenshtein         ... bench:       1,602 ns/iter (+/- 182)
test benches::bench_osa_distance                   ... bench:       3,095 ns/iter (+/- 144)
```

**Comment by dguo** [comment]
Hey, thanks. This looks awesome. My only concern is bumping the required Rust version to 1.31 since it was only released four months ago. Is that a requirement for hashbrown?

**Comment by lovasoa** [comment]
yes, it's a requirement of hashbrown : https://github.com/Amanieu/hashbrown/blob/master/CHANGELOG.md

**Comment by lovasoa** [comment]
Many crates depend on rust 1.31, since it marked the beginning of the 2018 edition.

**Comment by dguo** [comment]
Sounds good. A project that can't upgrade yet for some reason can always use an older version.

I published the change as [v0.9.1](https://crates.io/crates/strsim/0.9.1).

**Pull request merged**
