### PR TITLE
Add distances calculus against vector of strings

### PR DESCRIPTION
**Pull request by ovarene**
Add levenshtein_against_vec, damerau_levenshtein_against_vec,
jaro_against_vec, jaro_winkler_against_vec
to calculate the distances agains a vector of strings

### CODE REVIEW

**Comment by dguo** [comment]
Thanks for the contribution! I added some more tests and published it to [Crates](https://crates.io/crates/strsim).

**Comment by ovarene** [comment]
My pleasure. 

Thanks a lot

Best regards 
Olivier 



Sur 10 juin 2015 06:43, à 06:43, Danny Guo <notifications@github.com> a écrit:

**Comment by dguo** [comment]
Hi @ovarene, did you have a particular use case for these functions? It's a [one-liner](https://github.com/dguo/strsim-rs/blob/master/src/lib.rs#L125) now, so I'm thinking about removing them as functions and just providing an example in the readme.

**Comment by ovarene** [comment]
Thanks dany,

yes, I have use for those functions and they can be considered as helpers to avoir rewriting those constantly.
So, if you please could keep them, that would be useful for me.

Best regards

Olivier Varene

**Comment by dguo** [comment]
Did you get a chance to check out the one-liner though? 

Instead of using one of these helper functions, you could just do something like:

```rust
let distances = strings.iter().map(|b| jaro(target_string, b)).collect();
```

**Pull request merged**
