### PR TITLE
Improve Levenshtein performance

### PR DESCRIPTION
**Pull request by wdv4758h**
This is a Levenshtein implementation from https://github.com/wooorm/levenshtein-rs with some modification.

benchmark with current test code on my laptop:
bench

### CODE REVIEW

**Comment by dguo** [comment]
Hi, thank you for the PR. The speedups look great, but I'm concerned about using someone else's implementation, even if you modified it. I'm not sure if that means I would need to include a copy of wooorm's license as well. @wooorm, would you be comfortable with me merging this as is?

**Comment by wdv4758h** [comment]
yeah, let's make sure @wooorm is happy about this 👍

**Comment by dguo** [comment]
@wdv4758h said there are some modifications, and it doesn't seem like it's copying the full implementation. I'd also prefer to keep the dependency tree as small as possible.

But I'm happy to merge this and add a copyright statement to the existing MIT license. So I can just add `Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>` to the license, and that should suffice, yes?

**Comment by wooorm** [comment]
License: Yes I believe so!

Depending: Well, if there are modifications, I’d love to have them in `levenshtein-rs` as well! But, that’s my view coming from Node. Feel free to do whatever, it’s MIT licensed after all 😉

**Comment by dguo** [comment]
Sounds good!

I'll leave it up to @wdv4758h since he made the changes, but yes, I am totally for sharing improvements.

**Comment by wdv4758h** [comment]
sure, I can send a PR to `levenshtein-rs` too 😃

**Pull request merged**
